markdown: rdiscount
pygments: true
paginate: 8

safe: false

#站点基础配置
title: Superpippo's Lifebackup
#subTitle: backup my life
description: 这是 superpippo 的又一个博客，它是基于 Jekyll 搭建起来的。
#url: http://huang-wei.github.io
feed: /atom.xml

#菜单配置
nav:
  - text: 首页
    url: /index.html
  - text: 文章归档
    url: /archives.html
  - text: 01呓语
    url: /programming.html
  - text: 山与远方
    url: /life.html
  - text: 阅读人生
    url: /reading.html
  - text: 白加黑
    url: /football.html

#theme config
themes: /themes/violet

#配置你喜欢的顶部背景图片
headimg:
  - item: /themes/violet/images/hdbg01.jpg
  - item: /themes/violet/images/hdbg02.jpg
  - item: /themes/violet/images/hdbg03.jpg
  - item: /themes/violet/images/hdbg04.jpg

#关注我
follow:
  - class: fa-github
    url: http://github.com/huang-wei
  - class: fa-weibo
    url: http://weibo.com/hweicdl
  - class: fa-inbox
    url: mailto:superpippohw@gmail.com
  - class: fa-rss
    url: /atom.xml

#作者信息
authors:
  superpippo:
    display: Superpippo
  lisa:
    display: Lisa

#评论信息
disqus:
  config: false
  id: hweicdl

duoshuo:
  config: true
  id: hweicdl
